using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tilemap_editor
{
    public static class StringParsing
    {
        public static string[] customExitsRaw = new string[] 
        {
            "// 004C",
            "	.data32		=ScriptWarp_0000NULL",
            "// 004D",
            "	.data32		=ScriptWarp_0001Reptile_Rumble__level_start_",
            "// 004E",
            "	.data32		=ScriptWarp_0002Reptile_Rumble___Bonus_1",
            "// 004F",
            "	.data32		=ScriptWarp_0003Bouncy_Bonanza___Winky_Room",
            "// 0050",
            "	.data32		=ScriptWarp_0004Reptile_Rumble___Bonus_3",
            "// 0051",
            "	.data32		=ScriptWarp_0005Manic_Mincers___Bonus_1",
            "// 0052",
            "	.data32		=ScriptWarp_0006Jungle_Hijinxs___Bonus_1",
            "// 0053",
            "	.data32		=ScriptWarp_0007Bouncy_Bonanza__level_start_",
            "// 0054",
            "	.data32		=ScriptWarp_0008Jungle_Hijinxs__from_Bonus_1_",
            "// 0055",
            "	.data32		=ScriptWarp_0009Reptile_Rumble__from_Bonus_1_",
            "// 0056",
            "	.data32		=ScriptWarp_000AMisty_Mine__level_start_",
            "// 0057",
            "	.data32		=ScriptWarp_000BReptile_Rumble__from_Bonus_3_",
            "// 0058",
            "	.data32		=ScriptWarp_000CRopey_Rampage__level_start_",
            "// 0059",
            "	.data32		=ScriptWarp_000DOrang_utan_Gang__level_start_",
            "// 005A",
            "	.data32		=ScriptWarp_000EJungle_Hijinxs__from_house_",
            "// 005B",
            "	.data32		=ScriptWarp_000FRopey_Rampage__from_Save_",
            "// 005C",
            "	.data32		=ScriptWarp_0010Bouncy_Bonanza__from_Winky_Room_",
            "// 005D",
            "	.data32		=ScriptWarp_0011Bouncy_Bonanza___Bonus_2",
            "// 005E",
            "	.data32		=ScriptWarp_0012Manic_Mincers__level_start_",
            "// 005F",
            "	.data32		=ScriptWarp_0013Torchlight_Trouble__from_Save_",
            "// 0060",
            "	.data32		=ScriptWarp_0014Torchlight_Trouble__level_start_",
            "// 0061",
            "	.data32		=ScriptWarp_0015Bouncy_Bonanza__from_Save_",
            "// 0062",
            "	.data32		=ScriptWarp_0016Jungle_Hijinxs__level_start_",
            "// 0063",
            "	.data32		=ScriptWarp_0017Barrel_Cannon_Canyon__level_start_",
            "// 0064",
            "	.data32		=ScriptWarp_0018Elevator_Antics__level_start_",
            "// 0065",
            "	.data32		=ScriptWarp_0019Barrel_Cannon_Canyon__from_Save_",
            "// 0066",
            "	.data32		=ScriptWarp_001AJungle_Hijinxs___Bonus_2",
            "// 0067",
            "	.data32		=ScriptWarp_001BRopey_Rampage___Bonus_2",
            "// 0068",
            "	.data32		=ScriptWarp_001CRopey_Rampage___Bonus_1",
            "// 0069",
            "	.data32		=ScriptWarp_001DOrang_utan_Gang__from_Save_",
            "// 006A",
            "	.data32		=ScriptWarp_001EOrang_utan_Gang___Bonus_3",
            "// 006B",
            "	.data32		=ScriptWarp_001FOrang_utan_Gang___Bonus_2",
            "// 006C",
            "	.data32		=ScriptWarp_0020Orang_utan_Gang___Bonus_1",
            "// 006D",
            "	.data32		=ScriptWarp_0021_empty_jungle_room___boss_music___",
            "// 006E",
            "	.data32		=ScriptWarp_0022Poison_Pond__level_start_",
            "// 006F",
            "	.data32		=ScriptWarp_0023Elevator_Antics__from_Save_",
            "// 0070",
            "	.data32		=ScriptWarp_0024Snow_Barrel_Blast__level_start_",
            "// 0071",
            "	.data32		=ScriptWarp_0025Jungle_Hijinxs__from_Save_",
            "// 0072",
            "	.data32		=ScriptWarp_0026Reptile_Rumble__from_Save_",
            "// 0073",
            "	.data32		=ScriptWarp_0027Mine_Cart_Madness__level_start_",
            "// 0074",
            "	.data32		=ScriptWarp_0028Snow_Barrel_Blast__from_Save_",
            "// 0075",
            "	.data32		=ScriptWarp_0029Manic_Mincers__from_Save_",
            "// 0076",
            "	.data32		=ScriptWarp_002APoison_Pond__from_Save_",
            "// 0077",
            "	.data32		=ScriptWarp_002BPlatform_Perils__level_start_",
            "// 0078",
            "	.data32		=ScriptWarp_002CPlatform_Perils__from_Save_",
            "// 0079",
            "	.data32		=ScriptWarp_002DMisty_Mine__from_Save_",
            "// 007A",
            "	.data32		=ScriptWarp_002EMine_Cart_Carnage__level_start_",
            "// 007B",
            "	.data32		=ScriptWarp_002FTrick_Track_Trek__level_start_",
            "// 007C",
            "	.data32		=ScriptWarp_0030Tanked_Up_Trouble__level_start_",
            "// 007D",
            "	.data32		=ScriptWarp_0031Stop___Go_Station__level_start_",
            "// 007E",
            "	.data32		=ScriptWarp_0032Misty_Mine___Bonus_2",
            "// 007F",
            "	.data32		=ScriptWarp_0033Misty_Mine___Bonus_1",
            "// 0080",
            "	.data32		=ScriptWarp_0034Animal_Token_Room",
            "// 0081",
            "	.data32		=ScriptWarp_0035Millstone_Mayhem__from_warp_",
            "// 0082",
            "	.data32		=ScriptWarp_0036Loopy_Lights__level_start_",
            "// 0083",
            "	.data32		=ScriptWarp_0037Loopy_Lights___Bonus_2",
            "// 0084",
            "	.data32		=ScriptWarp_0038Mine_Cart_Carnage__from_Save_",
            "// 0085",
            "	.data32		=ScriptWarp_0039Trick_Track_Trek__from_Save_",
            "// 0086",
            "	.data32		=ScriptWarp_003ATanked_Up_Trouble__from_Save_",
            "// 0087",
            "	.data32		=ScriptWarp_003BMine_Cart_Madness__from_Save_",
            "// 0088",
            "	.data32		=ScriptWarp_003CStop___Go_Station__from_Save_",
            "// 0089",
            "	.data32		=ScriptWarp_003DLoopy_Lights__from_Save_",
            "// 008A",
            "	.data32		=ScriptWarp_003ECroctopus_Chase__level_start_",
            "// 008B",
            "	.data32		=ScriptWarp_003FCroctopus_Chase__from_Save_",
            "// 008C",
            "	.data32		=ScriptWarp_0040Oil_Drum_Alley__level_start_",
            "// 008D",
            "	.data32		=ScriptWarp_0041Blackout_Basement__level_start_",
            "// 008E",
            "	.data32		=ScriptWarp_0042Millstone_Mayhem__level_start_",
            "// 008F",
            "	.data32		=ScriptWarp_0043Temple_Tempest__level_start_",
            "// 0090",
            "	.data32		=ScriptWarp_0044Oil_Drum_Alley__from_Save_",
            "// 0091",
            "	.data32		=ScriptWarp_0045Blackout_Basement__from_Save_",
            "// 0092",
            "	.data32		=ScriptWarp_0046Barrel_Cannon_Canyon___Bonus_1",
            "// 0093",
            "	.data32		=ScriptWarp_0047Kong_s_Banana_Hoard__empty_",
            "// 0094",
            "	.data32		=ScriptWarp_0048Reptile_Rumble___Bonus_2",
            "// 0095",
            "	.data32		=ScriptWarp_0049Loopy_Lights___Bonus_1",
            "// 0096",
            "	.data32		=ScriptWarp_004AStop___Go_Station___Bonus_2",
            "// 0097",
            "	.data32		=ScriptWarp_004BStop___Go_Station___Bonus_1",
            "// 0098",
            "	.data32		=ScriptWarp_004CKong_s_Banana_Hoard__full_",
            "// 0099",
            "	.data32		=ScriptWarp_004DMine_Cart_Madness___Bonus_1",
            "// 009A",
            "	.data32		=ScriptWarp_004EPlatform_Perils___Bonus_1",
            "// 009B",
            "	.data32		=ScriptWarp_004FWinky_s_Walkway___Bonus_1",
            "// 009C",
            "	.data32		=ScriptWarp_0050Platform_Perils___Bonus_2",
            "// 009D",
            "	.data32		=ScriptWarp_0051Winky_s_Walkway__from_Bonus_1_",
            "// 009E",
            "	.data32		=ScriptWarp_0052Temple_Tempest___Bonus_1",
            "// 009F",
            "	.data32		=ScriptWarp_0053Temple_Tempest___Bonus_2",
            "// 00A0",
            "	.data32		=ScriptWarp_0054Tree_Top_Town__warp_",
            "// 00A1",
            "	.data32		=ScriptWarp_0055Millstone_Mayhem___Bonus_1",
            "// 00A2",
            "	.data32		=ScriptWarp_0056Millstone_Mayhem___Bonus_2",
            "// 00A3",
            "	.data32		=ScriptWarp_0057Millstone_Mayhem___Bonus_3",
            "// 00A4",
            "	.data32		=ScriptWarp_0058Millstone_Mayhem__from_Save_",
            "// 00A5",
            "	.data32		=ScriptWarp_0059Temple_Tempest__from_Save_",
            "// 00A6",
            "	.data32		=ScriptWarp_005AOrang_utan_Gang___Bonus_5",
            "// 00A7",
            "	.data32		=ScriptWarp_005BOrang_utan_Gang___Bonus_4",
            "// 00A8",
            "	.data32		=ScriptWarp_005CKong_s_Cabin",
            "// 00A9",
            "	.data32		=ScriptWarp_005DBarrel_Cannon_Canyon___Bonus_2",
            "// 00AA",
            "	.data32		=ScriptWarp_005ECredits",
            "// 00AB",
            "	.data32		=ScriptWarp_005FJungle_Hijinxs__from_Kong_s_Banana_Hoard_",
            "// 00AC",
            "	.data32		=ScriptWarp_0060Oil_Drum_Alley___Bonus_4",
            "// 00AD",
            "	.data32		=ScriptWarp_0061Oil_Drum_Alley___Bonus_2",
            "// 00AE",
            "	.data32		=ScriptWarp_0062Slipslide_Ride__warp_",
            "// 00AF",
            "	.data32		=ScriptWarp_0063Oil_Drum_Alley___Bonus_1",
            "// 00B0",
            "	.data32		=ScriptWarp_0064Blackout_Basement___Bonus_1",
            "// 00B1",
            "	.data32		=ScriptWarp_0065Vulture_Culture__warp_",
            "// 00B2",
            "	.data32		=ScriptWarp_0066Snow_Barrel_Blast___Bonus_3",
            "// 00B3",
            "	.data32		=ScriptWarp_0067Snow_Barrel_Blast___Bonus_1",
            "// 00B4",
            "	.data32		=ScriptWarp_0068Gangplank_Galleon",
            "// 00B5",
            "	.data32		=ScriptWarp_0069Snow_Barrel_Blast___Bonus_2",
            "// 00B6",
            "	.data32		=ScriptWarp_006AIce_Age_Alley___Bonus_1",
            "// 00B7",
            "	.data32		=ScriptWarp_006BIce_Age_Alley___Bonus_2",
            "// 00B8",
            "	.data32		=ScriptWarp_006CExpresso_Bonus",
            "// 00B9",
            "	.data32		=ScriptWarp_006DSlipslide_Ride__level_start_",
            "// 00BA",
            "	.data32		=ScriptWarp_006EJungle_Hijinxs__from_Bonus_2_",
            "// 00BB",
            "	.data32		=ScriptWarp_006FRopey_Rampage__from_Bonus_1_",
            "// 00BC",
            "	.data32		=ScriptWarp_0070Ropey_Rampage__from_Bonus_2_",
            "// 00BD",
            "	.data32		=ScriptWarp_0071Orang_utan_Gang__from_Bonus_4_",
            "// 00BE",
            "	.data32		=ScriptWarp_0072Orang_utan_Gang__from_Bonus_2_",
            "// 00BF",
            "	.data32		=ScriptWarp_0073Orang_utan_Gang__from_Bonus_1_",
            "// 00C0",
            "	.data32		=ScriptWarp_0074Orang_utan_Gang__from_Bonus_3_",
            "// 00C1",
            "	.data32		=ScriptWarp_0075Orang_utan_Gang__from_Bonus_5_",
            "// 00C2",
            "	.data32		=ScriptWarp_0076Barrel_Cannon_Canyon__from_Bonus_1_",
            "// 00C3",
            "	.data32		=ScriptWarp_0077Barrel_Cannon_Canyon__from_Bonus_2_",
            "// 00C4",
            "	.data32		=ScriptWarp_0078Bouncy_Bonanza__from_Bonus_1_",
            "// 00C5",
            "	.data32		=ScriptWarp_0079Bouncy_Bonanza__from_Bonus_2_",
            "// 00C6",
            "	.data32		=ScriptWarp_007AManic_Mincers__from_Bonus_1_",
            "// 00C7",
            "	.data32		=ScriptWarp_007BManic_Mincers__from_Ledge_Room_",
            "// 00C8",
            "	.data32		=ScriptWarp_007CManic_Mincers__from_Bonus_2_",
            "// 00C9",
            "	.data32		=ScriptWarp_007DElevator_Antics__from_Bonus_1_",
            "// 00CA",
            "	.data32		=ScriptWarp_007EElevator_Antics__from_Bonus_2_",
            "// 00CB",
            "	.data32		=ScriptWarp_007FElevator_Antics__from_Bonus_3_",
            "// 00CC",
            "	.data32		=ScriptWarp_0080Misty_Mine__from_Bonus_1_",
            "// 00CD",
            "	.data32		=ScriptWarp_0081Misty_Mine__from_Bonus_2_",
            "// 00CE",
            "	.data32		=ScriptWarp_0082Stop___Go_Station__from_Bonus_1_",
            "// 00CF",
            "	.data32		=ScriptWarp_0083Stop___Go_Station__from_Bonus_2_",
            "// 00D0",
            "	.data32		=ScriptWarp_0084Loopy_Lights__from_Bonus_1_",
            "// 00D1",
            "	.data32		=ScriptWarp_0085Loopy_Lights__from_Bonus_2_",
            "// 00D2",
            "	.data32		=ScriptWarp_0086Platform_Perils__from_Bonus_1_",
            "// 00D3",
            "	.data32		=ScriptWarp_0087Platform_Perils__from_Bonus_2_",
            "// 00D4",
            "	.data32		=ScriptWarp_0088Trick_Track_Trek__from_Bonus_1_",
            "// 00D5",
            "	.data32		=ScriptWarp_0089Trick_Track_Trek__from_Bonus_3_",
            "// 00D6",
            "	.data32		=ScriptWarp_008ATrick_Track_Trek__from_Bonus_2_",
            "// 00D7",
            "	.data32		=ScriptWarp_008BTanked_Up_Trouble__from_Bonus_1_",
            "// 00D8",
            "	.data32		=ScriptWarp_008CMine_Cart_Madness__from_Bonus_1_",
            "// 00D9",
            "	.data32		=ScriptWarp_008DMine_Cart_Madness__from_Bonus_2_",
            "// 00DA",
            "	.data32		=ScriptWarp_008EMine_Cart_Madness__from_Bonus_3_",
            "// 00DB",
            "	.data32		=ScriptWarp_008FOil_Drum_Alley__from_Bonus_1_",
            "// 00DC",
            "	.data32		=ScriptWarp_0090Oil_Drum_Alley__from_Bonus_2_3_",
            "// 00DD",
            "	.data32		=ScriptWarp_0091Oil_Drum_Alley__from_Bonus_4_",
            "// 00DE",
            "	.data32		=ScriptWarp_0092Blackout_Basement__from_Bonus_1_",
            "// 00DF",
            "	.data32		=ScriptWarp_0093Blackout_Basement__from_Bonus_2_",
            "// 00E0",
            "	.data32		=ScriptWarp_0094Snow_Barrel_Blast__from_Bonus_1_",
            "// 00E1",
            "	.data32		=ScriptWarp_0095Snow_Barrel_Blast__from_Bonus_2_",
            "// 00E2",
            "	.data32		=ScriptWarp_0096Snow_Barrel_Blast__from_Bonus_3_",
            "// 00E3",
            "	.data32		=ScriptWarp_0097Bouncy_Bonanza___Bonus_1",
            "// 00E4",
            "	.data32		=ScriptWarp_0098Manic_Mincers___Bonus_2",
            "// 00E5",
            "	.data32		=ScriptWarp_0099Manic_Mincers___Ledge_Room",
            "// 00E6",
            "	.data32		=ScriptWarp_009AElevator_Antics___Bonus_1",
            "// 00E7",
            "	.data32		=ScriptWarp_009BElevator_Antics___Bonus_2",
            "// 00E8",
            "	.data32		=ScriptWarp_009CElevator_Antics___Bonus_3",
            "// 00E9",
            "	.data32		=ScriptWarp_009DTrick_Track_Trek___Bonus_3",
            "// 00EA",
            "	.data32		=ScriptWarp_009ETrick_Track_Trek___Bonus_2",
            "// 00EB",
            "	.data32		=ScriptWarp_009FTanked_Up_Trouble___Bonus_1",
            "// 00EC",
            "	.data32		=ScriptWarp_00A0Mine_Cart_Madness___Bonus_2",
            "// 00ED",
            "	.data32		=ScriptWarp_00A1Trick_Track_Trek___Bonus_1",
            "// 00EE",
            "	.data32		=ScriptWarp_00A2Mine_Cart_Madness___Bonus_3",
            "// 00EF",
            "	.data32		=ScriptWarp_00A3Blackout_Basement___Bonus_2",
            "// 00F0",
            "	.data32		=ScriptWarp_00A4Tree_Top_Town__level_start_",
            "// 00F1",
            "	.data32		=ScriptWarp_00A5Vulture_Culture__level_start_",
            "// 00F2",
            "	.data32		=ScriptWarp_00A6Enguarde_Bonus",
            "// 00F3",
            "	.data32		=ScriptWarp_00A7Ice_Age_Alley__level_start_",
            "// 00F4",
            "	.data32		=ScriptWarp_00A8Ice_Age_Alley__from_Save_",
            "// 00F5",
            "	.data32		=ScriptWarp_00A9Tree_Top_Town__from_Save_",
            "// 00F6",
            "	.data32		=ScriptWarp_00AAVulture_Culture__from_Save_",
            "// 00F7",
            "	.data32		=ScriptWarp_00ABSlipslide_Ride__from_Save_",
            "// 00F8",
            "	.data32		=ScriptWarp_00ACIce_Age_Alley__from_Bonus_1_",
            "// 00F9",
            "	.data32		=ScriptWarp_00ADIce_Age_Alley__from_Bonus_2_",
            "// 00FA",
            "	.data32		=ScriptWarp_00AEMillstone_Mayhem__from_Bonus_1_",
            "// 00FB",
            "	.data32		=ScriptWarp_00AFMillstone_Mayhem__from_Bonus_2_",
            "// 00FC",
            "	.data32		=ScriptWarp_00B0Millstone_Mayhem__from_Bonus_3_",
            "// 00FD",
            "	.data32		=ScriptWarp_00B1Temple_Tempest__from_Bonus_1_",
            "// 00FE",
            "	.data32		=ScriptWarp_00B2Temple_Tempest__from_Bonus_2_",
            "// 00FF",
            "	.data32		=ScriptWarp_00B3Tree_Top_Town___Bonus_2",
            "// 0100",
            "	.data32		=ScriptWarp_00B4Tree_Top_Town___Bonus_1",
            "// 0101",
            "	.data32		=ScriptWarp_00B5Tree_Top_Town__from_Bonus_1_",
            "// 0102",
            "	.data32		=ScriptWarp_00B6Tree_Top_Town__from_Bonus_2_",
            "// 0103",
            "	.data32		=ScriptWarp_00B7Vulture_Culture___Bonus_1",
            "// 0104",
            "	.data32		=ScriptWarp_00B8Vulture_Culture___Bonus_2",
            "// 0105",
            "	.data32		=ScriptWarp_00B9Vulture_Culture___Bonus_3",
            "// 0106",
            "	.data32		=ScriptWarp_00BAVulture_Culture__from_Bonus_1_",
            "// 0107",
            "	.data32		=ScriptWarp_00BBVulture_Culture__from_Bonus_2_",
            "// 0108",
            "	.data32		=ScriptWarp_00BCVulture_Culture__from_Bonus_3_",
            "// 0109",
            "	.data32		=ScriptWarp_00BDTrick_Track_Trek__warp_",
            "// 010A",
            "	.data32		=ScriptWarp_00BEOil_Drum_Alley___Bonus_3",
            "// 010B",
            "	.data32		=ScriptWarp_00BFCoral_Capers__level_start_",
            "// 010C",
            "	.data32		=ScriptWarp_00C0Coral_Capers__from_Save_",
            "// 010D",
            "	.data32		=ScriptWarp_00C1Torchlight_Trouble___Bonus_1",
            "// 010E",
            "	.data32		=ScriptWarp_00C2Torchlight_Trouble__from_Bonus_1_",
            "// 010F",
            "	.data32		=ScriptWarp_00C3Torchlight_Trouble___Bonus_2",
            "// 0110",
            "	.data32		=ScriptWarp_00C4Torchlight_Trouble__from_Bonus_2_",
            "// 0111",
            "	.data32		=ScriptWarp_00C5Slipslide_Ride___Bonus_2",
            "// 0112",
            "	.data32		=ScriptWarp_00C6Slipslide_Ride___Bonus_3",
            "// 0113",
            "	.data32		=ScriptWarp_00C7Slipslide_Ride__from_Bonus_1_",
            "// 0114",
            "	.data32		=ScriptWarp_00C8Slipslide_Ride__from_Bonus_2_",
            "// 0115",
            "	.data32		=ScriptWarp_00C9Reptile_Rumble__from_Bonus_2_",
            "// 0116",
            "	.data32		=ScriptWarp_00CASlipslide_Ride___Bonus_1",
            "// 0117",
            "	.data32		=ScriptWarp_00CBSlipslide_Ride__from_Bonus_3_",
            "// 0118",
            "	.data32		=ScriptWarp_00CCMine_Cart_Carnage__warp_",
            "// 0119",
            "	.data32		=ScriptWarp_00CDStop___Go_Station__warp_",
            "// 011A",
            "	.data32		=ScriptWarp_00CERope_Bridge_Rumble__level_start_",
            "// 011B",
            "	.data32		=ScriptWarp_00CFRope_Bridge_Rumble__from_Save_",
            "// 011C",
            "	.data32		=ScriptWarp_00D0Forest_Frenzy__level_start_",
            "// 011D",
            "	.data32		=ScriptWarp_00D1Forest_Frenzy__from_Save_",
            "// 011E",
            "	.data32		=ScriptWarp_00D2Rambi_Bonus",
            "// 011F",
            "	.data32		=ScriptWarp_00D3Winky_Bonus",
            "// 0120",
            "	.data32		=ScriptWarp_00D4Forest_Frenzy___Bonus_2",
            "// 0121",
            "	.data32		=ScriptWarp_00D5Rope_Bridge_Rumble___Bonus_1",
            "// 0122",
            "	.data32		=ScriptWarp_00D6Rope_Bridge_Rumble__from_Bonus_2_",
            "// 0123",
            "	.data32		=ScriptWarp_00D7Rope_Bridge_Rumble___Bonus_2",
            "// 0124",
            "	.data32		=ScriptWarp_00D8Rope_Bridge_Rumble__from_Bonus_1_",
            "// 0125",
            "	.data32		=ScriptWarp_00D9Winky_s_Walkway__level_start_",
            "// 0126",
            "	.data32		=ScriptWarp_00DAWinky_s_Walkway__from_Save_",
            "// 0127",
            "	.data32		=ScriptWarp_00DBForest_Frenzy__from_Bonus_2_",
            "// 0128",
            "	.data32		=ScriptWarp_00DCForest_Frenzy___Bonus_1",
            "// 0129",
            "	.data32		=ScriptWarp_00DDForest_Frenzy__from_Bonus_1_",
            "// 012A",
            "	.data32		=ScriptWarp_00DEClam_City__level_start_",
            "// 012B",
            "	.data32		=ScriptWarp_00DFClam_City__from_Save_",
            "// 012C",
            "	.data32		=ScriptWarp_00E0Very_Gnawty_s_Lair",
            "// 012D",
            "	.data32		=ScriptWarp_00E1Necky_s_Nuts",
            "// 012E",
            "	.data32		=ScriptWarp_00E2Really_Gnawty_Rampage",
            "// 012F",
            "	.data32		=ScriptWarp_00E3Boss_Dumb_Drum",
            "// 0130",
            "	.data32		=ScriptWarp_00E4Necky_s_Revenge",
            "// 0131",
            "	.data32		=ScriptWarp_00E5Bumble_B_Rumble",

        };
        public static string[] CustomObjectList (string[] str)
        {
            List<string> @return = new List<string>();
            for (int i = 0; i < str.Length; i += 2)
            {
                // Extract code from raw
                var s1 = str[i + 0];
                s1 = s1.Substring(3);
                int code = Convert.ToInt32(s1, 16);

                // Extract string
                var s2 = str[i + 1];
                var indexOfFirst_ = s2.IndexOf('_');
                s2 = s2.Substring(indexOfFirst_ + 5);

                string final = $"{s2}={code.ToString("X4")}";
                @return.Add(final);
            }

            @return = @return.OrderBy(e => e).ToList();

            return @return.ToArray();
        }
    }
}
